# Generated by Django 3.1.2 on 2020-11-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='clip',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.FileField(upload_to=''),
        ),
    ]
