# Generated by Django 3.1.2 on 2020-11-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
